# Generated by Django 4.2.1 on 2023-06-07 15:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alunos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('matricula', models.CharField(max_length=255)),
                ('imagem', models.ImageField(upload_to='')),
                ('telefone', models.CharField(max_length=20)),
                ('endereco', models.TextField()),
                ('info', models.TextField()),
                ('data_nascimento', models.DateField()),
                ('ativo', models.BooleanField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Alunos',
            },
        ),
    ]
