# Generated by Django 4.2.1 on 2023-06-07 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0004_aluno_disciplina_disciplinarelacionada_documento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota',
            name='disciplina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alunos.disciplina'),
        ),
    ]
