# Generated by Django 4.2.1 on 2023-06-07 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0005_alter_nota_disciplina'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='matricula',
        ),
    ]
