# Generated by Django 4.2.1 on 2023-06-14 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0007_aluno_matricula'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nota',
            name='valor',
        ),
        migrations.AddField(
            model_name='nota',
            name='nota_01',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='nota',
            name='nota_02',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='nota',
            name='nota_03',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='matricula',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
